[package]
name = "lenia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorous = "1.0.12"
egui-macroquad = "0.15.0"
ndarray = "0.15.6"
rand = "0.8.5"